-- database.sql

DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    isDone TINYINT(1) DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deadline TIMESTAMP NULL
);

