-- drop_tables.sql

DROP TABLE IF EXISTS task_tags CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS blocks CASCADE;

DROP TYPE IF EXISTS status_types CASCADE;
DROP TYPE IF EXISTS priorities CASCADE;
DROP TYPE IF EXISTS task_types CASCADE;